name: build-test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: joinframework/join-ci:latest

    steps:
    - name: Fetch
      uses: actions/checkout@v2

    - name: Configure CMake
      run: pwd && ls -l ${{github.workspace}} && cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=Debug -DBUILD_SHARED_LIBS=OFF -DJOIN_ENABLE_TESTS=ON

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config Debug

    - name: Test
      run: cd ${{github.workspace}}/build && ctest --output-on-failure -C Debug

    - name: Generate coverage report
      run: lcov -d ${{github.workspace}}/build -c -o lcov.info

    - name: Cleanup coverage report
      run: lcov -d ${{github.workspace}}/build -r lcov.info '${{github.workspace}}/build/*' '${{github.workspace}}/core/tests/*' '${{github.workspace}}/crypto/tests/*' '${{github.workspace}}/network/tests/*' '${{github.workspace}}/sax/tests/*' '/usr/include/*' -o lcov.info

    - name: Deploy coverage
      uses: coverallsapp/github-action@v1.1.2
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        path-to-lcov: ./lcov.info
