name: build-test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: joinframework/join-ci:latest

    steps:
    - name: Fetch
      uses: actions/checkout@v2

    - name: Configure CMake
      run: pwd && echo $GITHUB_WORKSPACE && ls -l && cmake -G "Unix Makefiles" -B $GITHUB_WORKSPACE/build -DJOIN_ENABLE_TESTS=ON

    - name: Build
      run: pwd && echo $GITHUB_WORKSPACE && ls -l && cmake --build $GITHUB_WORKSPACE/build --config Debug

    - name: Test
      run: pwd && echo $GITHUB_WORKSPACE && ls -l && ctest --test-dir $GITHUB_WORKSPACE/build --output-on-failure -C Debug

    - name: Generate coverage report
      run: pwd && echo $GITHUB_WORKSPACE && ls -l && lcov --directory . --capture --output-file lcov.info

    - name: Cleanup coverage report
      run: pwd && echo $GITHUB_WORKSPACE && ls -l && lcov --remove lcov.info '$GITHUB_WORKSPACE/build/*' '$GITHUB_WORKSPACE/join/core/tests/*' '$GITHUB_WORKSPACE/join/sax/tests/*' '/usr/include/*' -o lcov.info

    - name: Deploy coverage
      uses: coverallsapp/github-action@v1.1.2
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        path-to-lcov: ./lcov.info
