name: build-test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: joinframework/join-ci:latest

    steps:
    - name: Fetch
      uses: actions/checkout@v2

    - name: Configure CMake
      run: cmake -G "Unix Makefiles" -B  ${GITHUB_WORKSPACE}/build -DJOIN_ENABLE_TESTS=ON

    - name: Build
      run: cmake --build ${GITHUB_WORKSPACE}/build --config Debug

    - name: Test
      run: ctest --test-dir ${GITHUB_WORKSPACE}/build --output-on-failure -C Debug

    - name: Generate coverage report
      run: lcov --directory ${GITHUB_WORKSPACE} --capture --output-file ${GITHUB_WORKSPACE}/lcov.info

    - name: Cleanup coverage report
      run: lcov --remove ${GITHUB_WORKSPACE}/lcov.info '${GITHUB_WORKSPACE}/build/*' '${GITHUB_WORKSPACE}/join/core/tests/*' '${GITHUB_WORKSPACE}/join/sax/tests/*' '/usr/include/*' -o ${GITHUB_WORKSPACE}/lcov.info

    - name: Deploy coverage
      uses: coverallsapp/github-action@v1.1.2
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        path-to-lcov: ${GITHUB_WORKSPACE}/lcov.info
