name: build-test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: joinframework/join-ci:latest

    steps:
    - name: Fetch
      uses: actions/checkout@v2

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=Debug -DBUILD_SHARED_LIBS=OFF -DJOIN_ENABLE_TESTS=ON

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config Debug

    - name: Test
      run: cd ${{github.workspace}}/build && ctest --output-on-failure -C Debug

    - name: Generate coverage report
      run: lcov --directory ${{github.workspace}} --capture --output-file lcov.info

    - name: Cleanup coverage report
      run: lcov --remove lcov.info '${{github.workspace}}/build/*' '${{github.workspace}}/join/core/tests/*' '${{github.workspace}}/join/crypto/tests/*' '${{github.workspace}}/join/network/tests/*' '${{github.workspace}}/join/sax/tests/*' '/usr/include/*' --output-file lcov.info

    - name: Deploy coverage
      uses: coverallsapp/github-action@v1.1.2
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        path-to-lcov: ${{github.workspace}}/lcov.info
