name: build

on:
  workflow_call:
    inputs:
      arch:
        type: string
        default: 'all'
      compiler:
        type: string
        default: 'all'
      coverage:
        type: boolean
        default: false
      scan:
        type: boolean
        default: false
      doc:
        type: boolean
        default: false

  workflow_dispatch:
    inputs:
      arch:
        type: choice
        options:
          - all
          - amd64
          - arm64
        default: 'all'
      compiler:
        type: choice
        options:
          - all
          - gcc
          - clang
        default: 'all'
      coverage:
        type: boolean
        default: false
      scan:
        type: boolean
        default: false
      doc:
        type: boolean
        default: false

jobs:
  format:
    runs-on: ubuntu-latest

    permissions:
      contents: read
     
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check formatting
        uses: jidicula/clang-format-action@v4.16.0
        with:
          clang-format-version: '18'
          check-path: '.'
          exclude-regex: 'build'

  build:
    strategy:
      matrix:
        arch: ${{ inputs.arch == 'all' && fromJson('["amd64", "arm64"]') || fromJson(format('["{0}"]', inputs.arch)) }}
        compiler: ${{ inputs.compiler == 'all' && fromJson('["gcc", "clang"]') || fromJson(format('["{0}"]', inputs.compiler)) }}

    runs-on: ${{ matrix.arch == 'amd64' && 'ubuntu-24.04' || 'ubuntu-24.04-arm' }}

    container:
      image: joinframework/join-ci:latest
      options: --privileged --sysctl net.ipv6.conf.all.disable_ipv6=0

    permissions:
      contents: read
      security-events: write

    defaults:
      run:
        shell: bash

    needs: format

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Build Environment
        if: inputs.scan || inputs.coverage
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Initialize codeql
        if: inputs.scan && matrix.arch == 'amd64'
        uses: github/codeql-action/init@v3

      - name: Configure
        if: inputs.scan || inputs.coverage
        run: cmake --preset ${{ matrix.compiler }}-debug

      - name: Build
        if: inputs.scan || inputs.coverage
        run: cmake --build --preset ${{ matrix.compiler }}-debug

      - name: Run codeql scan
        if: inputs.scan && matrix.arch == 'amd64'
        uses: github/codeql-action/analyze@v3

      - name: Run tests
        if: inputs.coverage
        run: ctest --preset ${{ matrix.compiler }}-debug

      - name: Generate coverage report
        if: inputs.coverage
        run: |
          lcov --directory build/${{ matrix.compiler }}/debug --capture --exclude "*/usr/include/*" --exclude '*/tests/*' --output-file lcov.info
          genhtml lcov.info --prefix $GITHUB_WORKSPACE --output-directory coverage

      - name: Upload coverage data to GitHub
        if: inputs.coverage
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.compiler }}-${{ matrix.arch }}-coverage-data
          path: lcov.info

      - name: Upload coverage report to GitHub
        if: inputs.coverage
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.compiler }}-${{ matrix.arch }}-coverage-report
          path: coverage/

      - name: Run doxygen
        if: inputs.doc && matrix.compiler == 'gcc' && matrix.arch == 'amd64'
        uses: mattnotmitt/doxygen-action@v1
        with:
          doxyfile-path: ./doxyfile
          working-directory: .

      - name: Upload documentation to GitHub
        if: inputs.doc && matrix.compiler == 'gcc' && matrix.arch == 'amd64'
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./doc/html

  deploy-coverage:
    if: inputs.coverage && (inputs.compiler == 'all' || inputs.compiler == 'gcc') && (inputs.arch == 'all' || inputs.arch == 'amd64')

    runs-on: ubuntu-latest

    container:
      image: joinframework/join-ci:latest

    permissions:
      contents: read

    needs: build

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download coverage data from GitHub
        uses: actions/download-artifact@v4
        with:
          name: gcc-amd64-coverage-data
          path: ./

      - name: Deploy coverage report to coveralls
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          files: lcov.info
          fail-on-error: true

      - name: Deploy coverage report to codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          flags: unittests
          files: lcov.info
          fail_ci_if_error: true

      - name: Deploy coverage report to codacy
        if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository
        uses: codacy/codacy-coverage-reporter-action@v1
        with:
          project-token: ${{secrets.CODACY_PROJECT_TOKEN}}
          coverage-reports: lcov.info

  deploy-pages:
    if: inputs.doc

    runs-on: ubuntu-latest

    container:
      image: joinframework/join-ci:latest

    permissions:
      contents: read
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    needs: build

    steps:
      - name: Deploy documentation to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
