name: build-test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Fetch
      uses: actions/checkout@v2

    - name: Install dependencies
      run: pwd && ls -l && sudo apt install libssl-dev lcov -y

    - name: Configure CMake
      run: pwd && ls -l && cmake -B ${{github.workspace}}/build -DJOIN_ENABLE_TESTS=ON

    - name: Build
      run: pwd && ls -l && cmake --build ${{github.workspace}}/build --config Debug

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: pwd && ls -l && ctest --output-on-failure -C Debug

    - name: Generate coverage report
      run: pwd && ls -l && lcov --directory . --capture --output-file lcov.info

    - name: Cleanup coverage report
      run: pwd && ls -l && lcov --remove lcov.info '${{github.workspace}}/build/*' '${{github.workspace}}/join/core/tests/*' '${{github.workspace}}/join/sax/tests/*' '/usr/include/*' -o lcov.info

    - name: Deploy coverage
      uses: coverallsapp/github-action@v1.1.2
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        path-to-lcov: ./lcov.info
