name: build-test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: joinframework/join-ci:latest

    steps:
    - name: Fetch
      uses: actions/checkout@v2

    - name: Configure CMake
      run: cmake -G "Unix Makefiles" -B /__w/join/join/build -DCMAKE_BUILD_TYPE=Debug -DJOIN_ENABLE_TESTS=ON -DJOIN_ENABLE_COVERAGE=ON

    - name: Build
      run: cmake --build /__w/join/join/build --config Debug

    - name: Test
      run: ctest --test-dir /__w/join/join/build --output-on-failure -C Debug

    - name: Generate coverage report
      run: lcov --directory . --capture --output-file lcov.info

    - name: Cleanup coverage report
      run: lcov --remove lcov.info '/__w/join/join/build/*' '/__w/join/join/join/core/tests/*' '/__w/join/join/join/crypto/tests/*' '/__w/join/join/join/network/tests/*' '/__w/join/join/join/sax/tests/*' '/usr/include/*' --output-file lcov.info

    - name: Deploy coverage report to coveralls
      uses: coverallsapp/github-action@v1.1.2
      with:
        github-token: ${{secrets.github_token}}
        path-to-lcov: /__w/join/join/lcov.info

    - name: Deploy coverage report to codecove
      uses: codecov/codecov-action@v2.1.0
      with:
        file: /__w/join/join/lcov.info

    - name: Deploy coverage report to codacy
      uses: codacy/codacy-coverage-reporter-action@v1
      with:
        coverage-reports: /__w/join/join/lcov.info
