name: build-test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: joinframework/join-ci:latest
    env:
      WORKSPACE: /__w/join/join

    steps:
    - name: Fetch
      uses: actions/checkout@v2

    - name: Configure CMake
      run: cmake -G "Unix Makefiles" -B $WORKSPACE/build -DJOIN_ENABLE_TESTS=ON -DJOIN_ENABLE_COVERAGE=ON

    - name: Build
      run: cmake --build $WORKSPACE/build --config Debug

    - name: Test
      run: ctest --test-dir $WORKSPACE/build --output-on-failure -C Debug

    - name: Generate coverage report
      run: lcov --directory . --capture --output-file lcov.info

    - name: Cleanup coverage report
      run: lcov --remove lcov.info '$WORKSPACE/build/*' '$WORKSPACE/join/core/tests/*' '$WORKSPACE/join/crypto/tests/*' '$WORKSPACE/join/network/tests/*' '$WORKSPACE/join/sax/tests/*' '/usr/include/*' --output-file lcov.info

    - name: Deploy coverage
      uses: coverallsapp/github-action@v1.1.2
      with:
        github-token: ${{secrets.github_token}}
        path-to-lcov: $WORKSPACE/lcov.info
