name: build-test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04
    container:
      image: joinframework/join-ci:latest
      options: --privileged

    steps:
    - name: Checkout
      uses: actions/checkout@v3.0.2

    - name: Configure
      run: cmake -B build -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Debug -DJOIN_ENABLE_COVERAGE=ON -DJOIN_ENABLE_TESTS=ON

    - name: Build
      run: cmake --build build --config Debug

    - name: Test
      run: ctest --test-dir build --output-on-failure -C Debug

    - name: Generate coverage report
      run: lcov --directory . --capture --output-file lcov.info

    - name: Cleanup coverage report
      run: lcov --remove lcov.info 'build/*' 'join/*/tests/*' '/usr/include/*' --output-file lcov.info

    - name: Deploy coverage report to coveralls
      uses: coverallsapp/github-action@1.1.3
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        path-to-lcov: lcov.info

    - name: Deploy coverage report to codecov
      uses: codecov/codecov-action@v3.1.1
      with:
        fail_ci_if_error: true
        token: ${{secrets.CODECOV_TOKEN}}
        file: lcov.info
        flags: unittests

    - name: Deploy coverage report to codacy
      uses: codacy/codacy-coverage-reporter-action@v1.3.0
      with:
        project-token: ${{secrets.CODACY_PROJECT_TOKEN}}
        coverage-reports: lcov.info
