name: build-test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04
    container:
      image: joinframework/join-ci:latest
      options: --privileged

    steps:
    - name: Checkout
      uses: actions/checkout@v3.0.2

    - name: Configure
      run: cmake -G "Unix Makefiles" -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=Debug -DJOIN_ENABLE_TESTS=ON -DJOIN_ENABLE_COVERAGE=ON

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config Debug

    - name: Test
      run: ctest --test-dir ${{github.workspace}}/build --output-on-failure -C Debug

    - name: Generate coverage report
      run: lcov --directory . --capture --output-file lcov.info

    - name: Cleanup coverage report
      run: lcov --remove lcov.info '/usr/include/*' '${{github.workspace}}/build/*' '${{github.workspace}}/join/*/tests/*' --output-file lcov.info

    - name: Deploy coverage report to coveralls
      uses: coverallsapp/github-action@1.1.3
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        path-to-lcov: ${{github.workspace}}/lcov.info

    - name: Deploy coverage report to codecov
      uses: codecov/codecov-action@v3.1.1
      with:
        fail_ci_if_error: true
        token: ${{secrets.CODECOV_TOKEN}}
        file: ${{github.workspace}}/lcov.info
        flags: unittests

    - name: Deploy coverage report to codacy
      uses: codacy/codacy-coverage-reporter-action@v1.3.0
      with:
        project-token: ${{secrets.CODACY_PROJECT_TOKEN}}
        coverage-reports: ${{github.workspace}}/lcov.info
