name: build

on:
  workflow_call:
    inputs:
      arch:
        type: string
        default: 'all'
      compiler:
        type: string
        default: 'all'
      coverage:
        type: boolean
        default: false
      scan:
        type: boolean
        default: false
      doc:
        type: boolean
        default: false

  workflow_dispatch:
    inputs:
      arch:
        type: choice
        options:
          - all
          - amd64
          - arm64
        default: 'all'
      compiler:
        type: choice
        options:
          - all
          - gcc
          - clang
        default: 'all'
      coverage:
        type: boolean
        default: false
      scan:
        type: boolean
        default: false
      doc:
        type: boolean
        default: false

jobs:
  format:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2

      - name: Check formatting
        uses: jidicula/clang-format-action@v4.18.0
        with:
          clang-format-version: '18'
          check-path: '.'
          exclude-regex: 'build'

  scan:
    if: inputs.scan

    needs: [format]

    runs-on: ubuntu-latest

    container:
      image: joinframework/join-ci:latest

    permissions:
      contents: read
      security-events: write

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2

      - name: Initialize codeql
        uses: github/codeql-action/init@v4.34.1
        with:
          languages: cpp

      - name: Configure
        run: cmake --preset gcc-debug

      - name: Build
        run: cmake --build --preset gcc-debug

      - name: Run codeql scan
        uses: github/codeql-action/analyze@v4.34.1

  build:
    needs: [format]

    strategy:
      fail-fast: false
      matrix:
        arch: ${{ inputs.arch == 'all' && fromJson('["amd64", "arm64"]') || fromJson(format('["{0}"]', inputs.arch)) }}
        compiler: ${{ inputs.compiler == 'all' && fromJson('["gcc", "clang"]') || fromJson(format('["{0}"]', inputs.compiler)) }}

    runs-on: ${{ matrix.arch == 'amd64' && 'ubuntu-24.04' || 'ubuntu-24.04-arm' }}

    container:
      image: joinframework/join-ci:latest
      options: --privileged --sysctl net.ipv6.conf.all.disable_ipv6=0

    permissions:
      contents: read

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2

      - name: Configure (release)
        run: cmake --preset ${{ matrix.compiler }}-release

      - name: Build (release)
        run: cmake --build --preset ${{ matrix.compiler }}-release

      - name: Run tests (release)
        run: ctest --preset ${{ matrix.compiler }}-release

      - name: Configure (debug)
        run: cmake --preset ${{ matrix.compiler }}-debug

      - name: Build (debug)
        run: cmake --build --preset ${{ matrix.compiler }}-debug

      - name: Run tests
        run: ctest --preset ${{ matrix.compiler }}-debug

      - name: Generate coverage report
        if: inputs.coverage && matrix.arch == 'amd64' && matrix.compiler == 'gcc'
        run: |
          lcov --directory build/${{ matrix.compiler }}/debug --capture --exclude "*/usr/include/*" --exclude '*/tests/*' --output-file lcov.info
          genhtml lcov.info --prefix $GITHUB_WORKSPACE --output-directory coverage

      - name: Upload coverage data to GitHub
        if: inputs.coverage && matrix.arch == 'amd64' && matrix.compiler == 'gcc'
        uses: actions/upload-artifact@v7.0.0
        with:
          name: ${{ matrix.compiler }}-${{ matrix.arch }}-coverage-data
          path: lcov.info

      - name: Upload coverage report to GitHub
        if: inputs.coverage && matrix.arch == 'amd64' && matrix.compiler == 'gcc'
        uses: actions/upload-artifact@v7.0.0
        with:
          name: ${{ matrix.compiler }}-${{ matrix.arch }}-coverage-report
          path: coverage/

  doc:
    if: inputs.doc

    needs: [format]

    runs-on: ubuntu-latest

    container:
      image: joinframework/join-ci:latest

    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2

      - name: Run doxygen
        uses: mattnotmitt/doxygen-action@v1.12.0
        with:
          doxyfile-path: ./doxyfile
          working-directory: .

      - name: Upload documentation to GitHub
        uses: actions/upload-pages-artifact@v4.0.0
        with:
          path: ./doc/html

  deploy-coverage:
    if: inputs.coverage && (inputs.compiler == 'all' || inputs.compiler == 'gcc') && (inputs.arch == 'all' || inputs.arch == 'amd64')

    needs: [build]

    runs-on: ubuntu-latest

    container:
      image: joinframework/join-ci:latest

    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2

      - name: Download coverage data from GitHub
        uses: actions/download-artifact@v7.0.0
        with:
          name: gcc-amd64-coverage-data
          path: ./

      - name: Deploy coverage report to coveralls
        uses: coverallsapp/github-action@v2.3.6
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          files: lcov.info
          fail-on-error: true

      - name: Deploy coverage report to codecov
        uses: codecov/codecov-action@v5.5.3
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          flags: unittests
          files: lcov.info
          fail_ci_if_error: true

      - name: Deploy coverage report to codacy
        if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository
        uses: codacy/codacy-coverage-reporter-action@v1.3.0
        with:
          project-token: ${{secrets.CODACY_PROJECT_TOKEN}}
          coverage-reports: lcov.info

  deploy-pages:
    if: inputs.doc

    needs: [doc]

    runs-on: ubuntu-latest

    container:
      image: joinframework/join-ci:latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    permissions:
      pages: write
      id-token: write

    steps:
      - name: Deploy documentation to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4.0.5
