name: Codacy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: "51 9 * * 5"

jobs:
  scan:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout
      uses: actions/checkout@v3.0.2

    - name: Perform codacy analysis
      uses: codacy/codacy-analysis-cli-action@v4.2.0
      with:
        project-token: ${{secrets.CODACY_PROJECT_TOKEN}}
        verbose: true
        output: results.sarif
        format: sarif
        gh-code-scanning-compat: true
        max-allowed-issues: 2147483647

    - name: Upload codacy scan report to github
      uses: github/codeql-action/upload-sarif@v2.12.1
      with:
        sarif_file: results.sarif
