name: test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  coverage:
    runs-on: ubuntu-22.04
    container:
      image: joinframework/join-ci:latest
      options: --privileged

    steps:
    - name: checkout
      uses: actions/checkout@v3.0.2

    - name: configure
      run: cmake -B build -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Debug -DJOIN_ENABLE_COVERAGE=ON -DJOIN_ENABLE_TESTS=ON

    - name: build
      run: cmake --build build --config Debug

    - name: run tests
      run: ctest --test-dir build --output-on-failure -C Debug

    - name: generate coverage report
      run: lcov --directory . --capture --output-file lcov.info

    - name: cleanup coverage report
      run: lcov --remove lcov.info "*/build/*" "*/tests/*" "/usr/include/*" --output-file coverage.info

    - name: deploy coverage report to coveralls
      uses: coverallsapp/github-action@1.1.3
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        path-to-lcov: coverage.info

    - name: deploy coverage report to codecov
      uses: codecov/codecov-action@v3.1.1
      with:
        fail_ci_if_error: true
        token: ${{secrets.CODECOV_TOKEN}}
        file: coverage.info
        flags: unittests

    - name: deploy coverage report to codacy
      uses: codacy/codacy-coverage-reporter-action@v1.3.0
      with:
        project-token: ${{secrets.CODACY_PROJECT_TOKEN}}
        coverage-reports: coverage.info
