name: pages

on:
  push:
    branches: [ main ]

    workflow_dispatch:

jobs:
  generate:
    uses: ./.github/workflows/build.yml

    secrets: inherit

    with:
      doc: true

    permissions:
      contents: read
      security-events: write
      pages: write
      id-token: write
