name: PR

on:
  push:
    branches: [ main ]

  pull_request:
    branches: [ main ]

jobs:
  ci:
    uses: ./.github/workflows/build.yml
    secrets: inherit
    inputs:
      scan: true
      coverage: true
      doc: false
