name: scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: "51 9 * * 5"

jobs:
  analyze:
    runs-on: ubuntu-22.04
    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        language: [ cpp ]

    steps:
    - name: install third party packages
      run: |
        sudo apt-get update
        sudo apt-get install --yes wget libssl-dev

    - name: checkout
      uses: actions/checkout@v3.0.2

    - name: configure
      run: cmake -B build -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Debug -DJOIN_ENABLE_TESTS=ON

    - name: perform codacy analysis
      uses: codacy/codacy-analysis-cli-action@v4.2.0
      with:
        project-token: ${{secrets.CODACY_PROJECT_TOKEN}}
        verbose: true
        output: results.sarif
        format: sarif
        gh-code-scanning-compat: true
        max-allowed-issues: 2147483647

    - name: upload codacy scan report to github
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: results.sarif
