name: security

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: "51 9 * * 5"

jobs:
  scan:
    runs-on: ubuntu-22.04

    container:
      image: joinframework/join-ci:latest
      options: --privileged

    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        language: [ cpp ]

    steps:
    - name: Checkout
      uses: actions/checkout@v3.0.2

    #- name: Perform codacy analysis
    #  uses: codacy/codacy-analysis-cli-action@v4.2.0
    #  with:
    #    project-token: ${{secrets.CODACY_PROJECT_TOKEN}}
    #    verbose: true
    #    output: results.sarif
    #    format: sarif
    #    gh-code-scanning-compat: true
    #    max-allowed-issues: 2147483647

    #- name: Upload codacy scan report to github
    #  uses: github/codeql-action/upload-sarif@v2
    #  with:
    #    sarif_file: results.sarif

    - name: Initialize codeql
      uses: github/codeql-action/init@v2
      with:
        languages: ${{matrix.language}}
        queries: +security-and-quality

    #- name: Build
    #  uses: github/codeql-action/autobuild@v2

    - name: Configure
      run: cmake -B _lgtm_build_dir -G "Unix Makefiles" -DJOIN_ENABLE_TESTS=ON

    - name: Build
      run: cmake --build _lgtm_build_dir --config Debug

    - name: Perform codeql analysis
      uses: github/codeql-action/analyze@v2
      with:
        category: "/language:${{ matrix.language }}"
