name: security

on:
  push:
    branches: [ main ]

  pull_request:
    branches: [ main ]

  schedule:
    - cron: "0 11 * * 0"

  workflow_dispatch:

jobs:
  scan:
    uses: ./.github/workflows/build.yml
    secrets: inherit
    with:
      scan: true
