name: test

on:
  push:
    branches: [ main ]

  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  coverage:
    uses: ./.github/workflows/build.yml
    secrets: inherit
    with:
      scan: false
      coverage: true
      doc: false
