name: test

on:
  pull_request:
    branches: [ main ]

jobs:
  coverage:
    uses: ./.github/workflows/build.yml
    secrets: inherit
    with:
      scan: false
      coverage: true
      doc: false
